name: Protocol tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyserial pytest

      - name: Run protocol tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q tests/test_serial_proto_sim.py
