name: Protocol tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install pyserial pytest
      - name: Run protocol tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q tests/test_serial_proto_sim.py